name: deploy-book

on:
  push:
    branches:
      - GGL  # Assicurati che questo sia il nome del tuo branch principale (potrebbe essere 'master')

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          # Installiamo la versione 1.0.0 che usa la sintassi corretta 'build .'
          pip install jupyter-book==1.0.0
          pip install sphinx-book-theme
      - name: Build the book
        run: |
          # Il comando corretto per la versione 1.0.0 Ã¨ solo 'build .'
          jupyter-book build .
      - name: Upload website artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jupyter-book-website
          path: _build/html/
      - name: Finish Process Placeholder
        run: echo "Processo completato. Cerca gli Artifacts nella tab Actions."

